# Generated by Django 4.0 on 2022-01-04 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('food_Id', models.BigAutoField(primary_key=True, serialize=False)),
                ('food_Name', models.CharField(max_length=30)),
                ('food_Type', models.CharField(max_length=30)),
                ('food_Price', models.FloatField()),
                ('food_Description', models.TextField()),
            ],
        ),
    ]
