# Generated by Django 3.2.9 on 2022-02-21 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodapp', '0002_food_food_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='food',
            name='food_Image',
        ),
    ]
